version: "3"

services:
  mysqldb:
    image: mysql:8.0.19
    container_name: mysqldb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    volumes:
      - ./data:/var/lib/mysql

volumes:
  data:
